#! /usr/bin/env bash

SCRIPT_DIR="$(dirname $(readlink -f $0))"
cd "$SCRIPT_DIR/.."
HOME=$PWD
echo Directory: $HOME

VERSION=$(python3 -c "import simphony; print(simphony.__version__)")
echo Version: $VERSION

FILE="$HOME/docs/changelog/$VERSION-changelog.md"
echo "Changelog file location: $FILE"
if test -f "$FILE"; 
then
    echo "Changelog file found."
else
    echo "ERROR: Changelog file missing, cannot create release."
    exit 1
fi

TAG_NAME=v$VERSION
echo $TAG_NAME

# git tag $TAG_NAME
# git push origin $TAG_NAME