#! /usr/bin/env bash
# Copyright © 2019-2020 Simphony Project Contributors and others (see AUTHORS.txt).
# The resources, libraries, and some source files under other terms (see NOTICE.txt).
#
# This file is part of Simphony.
#
# Simphony is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Simphony is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Simphony. If not, see <https://www.gnu.org/licenses/>.

SCRIPT_DIR="$(dirname $(readlink -f $0))"
cd "$SCRIPT_DIR/.."
HOME=$PWD
echo Directory: $HOME

VERSION=$(python3 -c "import simphony; print(simphony.__version__)")
echo Version: $VERSION

FILE="$HOME/docs/changelog/$VERSION-changelog.md"
echo "Changelog file location: $FILE"
if test -f "$FILE"; 
then
    echo "Changelog file found."
else
    echo "ERROR: Changelog file missing, cannot create release."
    exit 1
fi

TAG_NAME=v$VERSION
echo $TAG_NAME

git tag $TAG_NAME
git push origin $TAG_NAME
